### ISSUE TITLE
Getting no response from my intents

### ISSUE THREAD

**Issue by sukritchakravarty** [ndg63276/alexa-googlemaps#1]
@ndg63276 : I am trying to use this code and create something for myself but I am not getting the correct output from this code as well, so can you help me out with this.
Here is how this looks on Alexa skill side:
![image](https://user-images.githubusercontent.com/38478983/47199958-db86d780-d328-11e8-9eba-d2f147863612.png)

Lambda:
![image](https://user-images.githubusercontent.com/38478983/47199981-ffe2b400-d328-11e8-92be-97d0d7ab316e.png)

I am trying to run your code, once I am able to run your code then I can prepare something for myself.
Any help is appreciated.

**Comment by sukritchakravarty** [comment]
{
	"version": "1.0",
	"session": {
		"new": false,
		"sessionId": "amzn1.echo-api.session.8fed5aaf-e914-48ec-b06f-86d046deadb4",
		"application": {
			"applicationId": "amzn1.ask.skill.51eb4a26-1810-4c08-a350-4fb1aec7bb80"
		},
		"user": {
			"userId": "amzn1.ask.account.AGCKIPPO7NNVA7H4L6YTRV72PYBQ43GRU22PTEBO64V2HJZ4JJP5MSHYXZZPJCCCBWGMTNFX5ZOVU2NZWV66ECFSPLARMSIAMPQFAGN6G6LD2SADTOHMZ4VUBXHUYCBWTTUIFSPCS24YWXJPIMPT43QMJTUKNYOGEFSPCH5O7UL3QKAHXDKMXLY65WZNEXGF6CWTZYTTI732TXI"
		}
	},
	"context": {
		"System": {
			"application": {
				"applicationId": "amzn1.ask.skill.51eb4a26-1810-4c08-a350-4fb1aec7bb80"
			},
			"user": {
				"userId": "amzn1.ask.account.AGCKIPPO7NNVA7H4L6YTRV72PYBQ43GRU22PTEBO64V2HJZ4JJP5MSHYXZZPJCCCBWGMTNFX5ZOVU2NZWV66ECFSPLARMSIAMPQFAGN6G6LD2SADTOHMZ4VUBXHUYCBWTTUIFSPCS24YWXJPIMPT43QMJTUKNYOGEFSPCH5O7UL3QKAHXDKMXLY65WZNEXGF6CWTZYTTI732TXI"
			},
			"device": {
				"deviceId": "amzn1.ask.device.AEC6OH2GRCAUHNGOT5US2PEIM6FVISNSATJV3TGQXLJAZ3SOL4VMLB3HLCNHDFEECZTCHJJHMLH35225CCHWXU6ZDBXVF5L772SQPGGHRXNEDMYYHS32PF6Q2HJQCDMNU5GJ7KX4A3H6VOE5KA7ZNLRK5H3U7726FEHCXEQZSOYWXAMP5DRZK",
				"supportedInterfaces": {}
			},
			"apiEndpoint": "https://api.amazonalexa.com",
			"apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjUxZWI0YTI2LTE4MTAtNGMwOC1hMzUwLTRmYjFhZWM3YmI4MCIsImV4cCI6MTUzOTkzMTg0NiwiaWF0IjoxNTM5OTI4MjQ2LCJuYmYiOjE1Mzk5MjgyNDYsInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUVDNk9IMkdSQ0FVSE5HT1Q1VVMyUEVJTTZGVklTTlNBVEpWM1RHUVhMSkFaM1NPTDRWTUxCM0hMQ05IREZFRUNaVENISkpITUxIMzUyMjVDQ0hXWFU2WkRCWFZGNUw3NzJTUVBHR0hSWE5FRE1ZWUhTMzJQRjZRMkhKUUNETU5VNUdKN0tYNEEzSDZWT0U1S0E3Wk5MUks1SDNVNzcyNkZFSENYRVFaU09ZV1hBTVA1RFJaSyIsInVzZXJJZCI6ImFtem4xLmFzay5hY2NvdW50LkFHQ0tJUFBPN05OVkE3SDRMNllUUlY3MlBZQlE0M0dSVTIyUFRFQk82NFYySEpaNEpKUDVNU0hZWFpaUEpDQ0NCV0dNVE5GWDVaT1ZVMk5aV1Y2NkVDRlNQTEFSTVNJQU1QUUZBR042RzZMRDJTQURUT0hNWjRWVUJYSFVZQ0JXVFRVSUZTUENTMjRZV1hKUElNUFQ0M1FNSlRVS05ZT0dFRlNQQ0g1TzdVTDNRS0FIWERLTVhMWTY1V1pORVhHRjZDV1RaWVRUSTczMlRYSSJ9fQ.WnJrlkAD72n3Bf2e7BQco0grYS1kMpKvIn54F4pd329JA6523-4HQgmTx0oWaPkqXheRuCkiXaDWaeLcgk3skJt0ZbT-qLSAgpYeXW-WwkHORhhFiFTEJy2kYBUAEzv7nACNN2m09s4zWmA3PTHJWx2CmX_w4qYrzaOoSUDq96XV6LndgAuMxxT7XBFxSEhUun80BPY3YXko2ouYXmjDYHNN3YdFXUy9qXrQjWhEnyTfIswpXzyiIrZyio1qdH4MCRZ4_DBnrKYaI4Afeuy7cwm6wONEMAvxzVDTvyFPMuBzN1gHz0muJ-RMcq5qpzOgxnRkqRDEg_PEKvf3ephPlA"
		}
	},
	"request": {
		"type": "IntentRequest",
		"requestId": "amzn1.echo-api.request.1e4c297e-2851-4469-893d-e78a5e8c0636",
		"timestamp": "2018-10-19T05:50:46Z",
		"locale": "en-US",
		"intent": {
			"name": "GetDirectionsTo",
			"confirmationStatus": "NONE",
			"slots": {
				"healthex": {
					"name": "healthex",
					"confirmationStatus": "NONE"
				},
				"tocity": {
					"name": "tocity",
					"confirmationStatus": "NONE"
				},
				"fromcity": {
					"name": "fromcity",
					"confirmationStatus": "NONE"
				}
			}
		}
	}
}

This is the Json code.

**Comment by ndg63276** [comment]
Ok, firstly, when testing on the Alexa skill side, you don't need to type "getcommutetowork how is my commute", you can just put "how is my commute".

Next, try testing this json file. You can do this from the Alexa skill testing page by clicking on 'Manual JSON', pasting it in, and pressing Submit.

`{
"version": "1.0",
"session": {
"new": false,
"sessionId": "amzn1.echo-api.session.8fed5aaf-e914-48ec-b06f-86d046deadb4",
"application": {
"applicationId": "amzn1.ask.skill.51eb4a26-1810-4c08-a350-4fb1aec7bb80"
},
"user": {
"userId": "amzn1.ask.account.AGCKIPPO7NNVA7H4L6YTRV72PYBQ43GRU22PTEBO64V2HJZ4JJP5MSHYXZZPJCCCBWGMTNFX5ZOVU2NZWV66ECFSPLARMSIAMPQFAGN6G6LD2SADTOHMZ4VUBXHUYCBWTTUIFSPCS24YWXJPIMPT43QMJTUKNYOGEFSPCH5O7UL3QKAHXDKMXLY65WZNEXGF6CWTZYTTI732TXI"
}
},
"context": {
"System": {
"application": {
"applicationId": "amzn1.ask.skill.51eb4a26-1810-4c08-a350-4fb1aec7bb80"
},
"user": {
"userId": "amzn1.ask.account.AGCKIPPO7NNVA7H4L6YTRV72PYBQ43GRU22PTEBO64V2HJZ4JJP5MSHYXZZPJCCCBWGMTNFX5ZOVU2NZWV66ECFSPLARMSIAMPQFAGN6G6LD2SADTOHMZ4VUBXHUYCBWTTUIFSPCS24YWXJPIMPT43QMJTUKNYOGEFSPCH5O7UL3QKAHXDKMXLY65WZNEXGF6CWTZYTTI732TXI"
},
"device": {
"deviceId": "amzn1.ask.device.AEC6OH2GRCAUHNGOT5US2PEIM6FVISNSATJV3TGQXLJAZ3SOL4VMLB3HLCNHDFEECZTCHJJHMLH35225CCHWXU6ZDBXVF5L772SQPGGHRXNEDMYYHS32PF6Q2HJQCDMNU5GJ7KX4A3H6VOE5KA7ZNLRK5H3U7726FEHCXEQZSOYWXAMP5DRZK",
"supportedInterfaces": {}
},
"apiEndpoint": "https://api.amazonalexa.com",
"apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjUxZWI0YTI2LTE4MTAtNGMwOC1hMzUwLTRmYjFhZWM3YmI4MCIsImV4cCI6MTUzOTkzMTg0NiwiaWF0IjoxNTM5OTI4MjQ2LCJuYmYiOjE1Mzk5MjgyNDYsInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUVDNk9IMkdSQ0FVSE5HT1Q1VVMyUEVJTTZGVklTTlNBVEpWM1RHUVhMSkFaM1NPTDRWTUxCM0hMQ05IREZFRUNaVENISkpITUxIMzUyMjVDQ0hXWFU2WkRCWFZGNUw3NzJTUVBHR0hSWE5FRE1ZWUhTMzJQRjZRMkhKUUNETU5VNUdKN0tYNEEzSDZWT0U1S0E3Wk5MUks1SDNVNzcyNkZFSENYRVFaU09ZV1hBTVA1RFJaSyIsInVzZXJJZCI6ImFtem4xLmFzay5hY2NvdW50LkFHQ0tJUFBPN05OVkE3SDRMNllUUlY3MlBZQlE0M0dSVTIyUFRFQk82NFYySEpaNEpKUDVNU0hZWFpaUEpDQ0NCV0dNVE5GWDVaT1ZVMk5aV1Y2NkVDRlNQTEFSTVNJQU1QUUZBR042RzZMRDJTQURUT0hNWjRWVUJYSFVZQ0JXVFRVSUZTUENTMjRZV1hKUElNUFQ0M1FNSlRVS05ZT0dFRlNQQ0g1TzdVTDNRS0FIWERLTVhMWTY1V1pORVhHRjZDV1RaWVRUSTczMlRYSSJ9fQ.WnJrlkAD72n3Bf2e7BQco0grYS1kMpKvIn54F4pd329JA6523-4HQgmTx0oWaPkqXheRuCkiXaDWaeLcgk3skJt0ZbT-qLSAgpYeXW-WwkHORhhFiFTEJy2kYBUAEzv7nACNN2m09s4zWmA3PTHJWx2CmX_w4qYrzaOoSUDq96XV6LndgAuMxxT7XBFxSEhUun80BPY3YXko2ouYXmjDYHNN3YdFXUy9qXrQjWhEnyTfIswpXzyiIrZyio1qdH4MCRZ4_DBnrKYaI4Afeuy7cwm6wONEMAvxzVDTvyFPMuBzN1gHz0muJ-RMcq5qpzOgxnRkqRDEg_PEKvf3ephPlA"
}
},
	"request": {
		"type": "IntentRequest",
		"requestId": "amzn1.echo-api.request.dcfd2ef7-6d85-48d4-9bc5-c854592d9097",
		"timestamp": "2018-10-19T11:35:29Z",
		"locale": "en-GB",
		"intent": {
			"name": "GetCommuteToWork",
			"confirmationStatus": "NONE"
		}
	}
}`

**Comment by sukritchakravarty** [comment]
@ndg63276 : If I copy your JSON this is the response I get:
![image](https://user-images.githubusercontent.com/38478983/47228476-2c72ec00-d37a-11e8-8da1-f93791e0ec0d.png)

Where do I need to setup my address, I tried setting up my in alexa app but that also gives me the same message.

Also Can you tell me what am I missing for it to respond to me?

Here is the response JSON output:
{
	"status": "SUCCESSFUL",
	"result": {
		"skillExecutionInfo": {
			"invocationRequest": {
				"endpoint": "arn:aws:lambda:us-east-1:614456615802:function:GoogleMaps",
				"body": {
					"version": "1.0",
					"session": {
						"new": false,
						"sessionId": "amzn1.echo-api.session.8fed5aaf-e914-48ec-b06f-86d046deadb4",
						"application": {
							"applicationId": "amzn1.ask.skill.51eb4a26-1810-4c08-a350-4fb1aec7bb80"
						},
						"user": {
							"userId": "amzn1.ask.account.AGCKIPPO7NNVA7H4L6YTRV72PYBQ43GRU22PTEBO64V2HJZ4JJP5MSHYXZZPJCCCBWGMTNFX5ZOVU2NZWV66ECFSPLARMSIAMPQFAGN6G6LD2SADTOHMZ4VUBXHUYCBWTTUIFSPCS24YWXJPIMPT43QMJTUKNYOGEFSPCH5O7UL3QKAHXDKMXLY65WZNEXGF6CWTZYTTI732TXI"
						}
					},
					"context": {
						"System": {
							"application": {
								"applicationId": "amzn1.ask.skill.51eb4a26-1810-4c08-a350-4fb1aec7bb80"
							},
							"user": {
								"userId": "amzn1.ask.account.AGCKIPPO7NNVA7H4L6YTRV72PYBQ43GRU22PTEBO64V2HJZ4JJP5MSHYXZZPJCCCBWGMTNFX5ZOVU2NZWV66ECFSPLARMSIAMPQFAGN6G6LD2SADTOHMZ4VUBXHUYCBWTTUIFSPCS24YWXJPIMPT43QMJTUKNYOGEFSPCH5O7UL3QKAHXDKMXLY65WZNEXGF6CWTZYTTI732TXI"
							},
							"device": {
								"deviceId": "amzn1.ask.device.AEC6OH2GRCAUHNGOT5US2PEIM6FVISNSATJV3TGQXLJAZ3SOL4VMLB3HLCNHDFEECZTCHJJHMLH35225CCHWXU6ZDBXVF5L772SQPGGHRXNEDMYYHS32PF6Q2HJQCDMNU5GJ7KX4A3H6VOE5KA7ZNLRK5H3U7726FEHCXEQZSOYWXAMP5DRZK",
								"supportedInterfaces": {}
							},
							"apiEndpoint": "https://api.amazonalexa.com",
							"apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjUxZWI0YTI2LTE4MTAtNGMwOC1hMzUwLTRmYjFhZWM3YmI4MCIsImV4cCI6MTUzOTkzMTg0NiwiaWF0IjoxNTM5OTI4MjQ2LCJuYmYiOjE1Mzk5MjgyNDYsInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUVDNk9IMkdSQ0FVSE5HT1Q1VVMyUEVJTTZGVklTTlNBVEpWM1RHUVhMSkFaM1NPTDRWTUxCM0hMQ05IREZFRUNaVENISkpITUxIMzUyMjVDQ0hXWFU2WkRCWFZGNUw3NzJTUVBHR0hSWE5FRE1ZWUhTMzJQRjZRMkhKUUNETU5VNUdKN0tYNEEzSDZWT0U1S0E3Wk5MUks1SDNVNzcyNkZFSENYRVFaU09ZV1hBTVA1RFJaSyIsInVzZXJJZCI6ImFtem4xLmFzay5hY2NvdW50LkFHQ0tJUFBPN05OVkE3SDRMNllUUlY3MlBZQlE0M0dSVTIyUFRFQk82NFYySEpaNEpKUDVNU0hZWFpaUEpDQ0NCV0dNVE5GWDVaT1ZVMk5aV1Y2NkVDRlNQTEFSTVNJQU1QUUZBR042RzZMRDJTQURUT0hNWjRWVUJYSFVZQ0JXVFRVSUZTUENTMjRZV1hKUElNUFQ0M1FNSlRVS05ZT0dFRlNQQ0g1TzdVTDNRS0FIWERLTVhMWTY1V1pORVhHRjZDV1RaWVRUSTczMlRYSSJ9fQ.WnJrlkAD72n3Bf2e7BQco0grYS1kMpKvIn54F4pd329JA6523-4HQgmTx0oWaPkqXheRuCkiXaDWaeLcgk3skJt0ZbT-qLSAgpYeXW-WwkHORhhFiFTEJy2kYBUAEzv7nACNN2m09s4zWmA3PTHJWx2CmX_w4qYrzaOoSUDq96XV6LndgAuMxxT7XBFxSEhUun80BPY3YXko2ouYXmjDYHNN3YdFXUy9qXrQjWhEnyTfIswpXzyiIrZyio1qdH4MCRZ4_DBnrKYaI4Afeuy7cwm6wONEMAvxzVDTvyFPMuBzN1gHz0muJ-RMcq5qpzOgxnRkqRDEg_PEKvf3ephPlA"
						}
					},
					"request": {
						"type": "IntentRequest",
						"requestId": "amzn1.echo-api.request.dcfd2ef7-6d85-48d4-9bc5-c854592d9097",
						"timestamp": "2018-10-19T11:35:29Z",
						"locale": "en-GB",
						"intent": {
							"name": "GetCommuteToWork",
							"confirmationStatus": "NONE"
						}
					}
				}
			},
			"invocationResponse": {
				"body": {
					"version": "1.0",
					"sessionAttributes": {},
					"response": {
						"outputSpeech": {
							"type": "PlainText",
							"text": "Sorry, I do not know your address. Please check the settings in the Alexa app."
						},
						"card": {
							"type": "Simple",
							"title": "Google Maps error",
							"content": "Sorry, I do not know your address. Please check the settings in the Alexa app."
						},
						"reprompt": {
							"outputSpeech": {
								"type": "PlainText",
								"text": null
							}
						},
						"shouldEndSession": true
					}
				}
			},
			"metrics": {
				"skillExecutionTimeInMilliseconds": 361
			}
		},
		"error": null
	}
}

**Comment by sukritchakravarty** [comment]
@ndg63276 : This also gives me error:

{
	"version": "1.0",
	"session": {
		"new": false,
		"sessionId": "amzn1.echo-api.session.5ae04b3d-fd9f-4b31-8262-e8a48bd9c059",
		"application": {
			"applicationId": "amzn1.ask.skill.51eb4a26-1810-4c08-a350-4fb1aec7bb80"
		},
		"user": {
			"userId": "amzn1.ask.account.AGCKIPPO7NNVA7H4L6YTRV72PYBQ43GRU22PTEBO64V2HJZ4JJP5MSHYXZZPJCCCBWGMTNFX5ZOVU2NZWV66ECFSPLARMSIAMPQFAGN6G6LD2SADTOHMZ4VUBXHUYCBWTTUIFSPCS24YWXJPIMPT43QMJTUKNYOGEFSPCH5O7UL3QKAHXDKMXLY65WZNEXGF6CWTZYTTI732TXI"
		}
	},
	"context": {
		"System": {
			"application": {
				"applicationId": "amzn1.ask.skill.51eb4a26-1810-4c08-a350-4fb1aec7bb80"
			},
			"user": {
				"userId": "amzn1.ask.account.AGCKIPPO7NNVA7H4L6YTRV72PYBQ43GRU22PTEBO64V2HJZ4JJP5MSHYXZZPJCCCBWGMTNFX5ZOVU2NZWV66ECFSPLARMSIAMPQFAGN6G6LD2SADTOHMZ4VUBXHUYCBWTTUIFSPCS24YWXJPIMPT43QMJTUKNYOGEFSPCH5O7UL3QKAHXDKMXLY65WZNEXGF6CWTZYTTI732TXI"
			},
			"device": {
				"deviceId": "amzn1.ask.device.AEC6OH2GRCAUHNGOT5US2PEIM6FVISNSATJV3TGQXLJAZ3SOL4VMLB3HLCNHDFEECZTCHJJHMLH35225CCHWXU6ZDBXVF5L772SQPGGHRXNEDMYYHS32PF6Q2HJQCDMNU5GJ7KX4A3H6VOE5KA7ZNLRK5H3U7726FEHCXEQZSOYWXAMP5DRZK",
				"supportedInterfaces": {}
			},
			"apiEndpoint": "https://api.amazonalexa.com",
			"apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjUxZWI0YTI2LTE4MTAtNGMwOC1hMzUwLTRmYjFhZWM3YmI4MCIsImV4cCI6MTUzOTk5MDkxOCwiaWF0IjoxNTM5OTg3MzE4LCJuYmYiOjE1Mzk5ODczMTgsInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUVDNk9IMkdSQ0FVSE5HT1Q1VVMyUEVJTTZGVklTTlNBVEpWM1RHUVhMSkFaM1NPTDRWTUxCM0hMQ05IREZFRUNaVENISkpITUxIMzUyMjVDQ0hXWFU2WkRCWFZGNUw3NzJTUVBHR0hSWE5FRE1ZWUhTMzJQRjZRMkhKUUNETU5VNUdKN0tYNEEzSDZWT0U1S0E3Wk5MUks1SDNVNzcyNkZFSENYRVFaU09ZV1hBTVA1RFJaSyIsInVzZXJJZCI6ImFtem4xLmFzay5hY2NvdW50LkFHQ0tJUFBPN05OVkE3SDRMNllUUlY3MlBZQlE0M0dSVTIyUFRFQk82NFYySEpaNEpKUDVNU0hZWFpaUEpDQ0NCV0dNVE5GWDVaT1ZVMk5aV1Y2NkVDRlNQTEFSTVNJQU1QUUZBR042RzZMRDJTQURUT0hNWjRWVUJYSFVZQ0JXVFRVSUZTUENTMjRZV1hKUElNUFQ0M1FNSlRVS05ZT0dFRlNQQ0g1TzdVTDNRS0FIWERLTVhMWTY1V1pORVhHRjZDV1RaWVRUSTczMlRYSSJ9fQ.FJeXktqW362Ttbs3FaJnYFfUMQnWoTJ9zCSYWDlfsrG6ZTSHV28RzADvQEfA1scJiIZNFZ30Bn0FTO98kHobk-vM2fbX7j34VPgI7eUV8mY1JN-wlkYPXzUiFLZOUMOeYYUnXuX3efT48Yp2TQ0iS0lYHgZEY-1sOyTLhK1EH1RtBj7uLkbvfBdfakOmQOaf9_tj4OO7WT1RyY3QFhPa2oEC6ICYXavlb1Fv8V2asTxnguKBVZCvaRPBjDOpbbtV6Rh8RNZ-04HitaUFJB39CCxIX4WCkAT9OTSaIn_wpsNoqtJ3AODm7vEyn0yuO-soZApyXHVBwiGsvGFzAEVQIQ"
		}
	},
	"request": {
		"type": "IntentRequest",
		"requestId": "amzn1.echo-api.request.2a9d9590-146e-4741-b04f-8e5fc163b7bc",
		"timestamp": "2018-10-19T22:15:18Z",
		"locale": "en-US",
		"intent": {
			"name": "GetDirectionsTo",
			"confirmationStatus": "NONE",
			"slots": {
				"healthex": {
					"name": "healthex",
					"confirmationStatus": "NONE"
				},
				"tocity": {
					"name": "tocity",
					"value": "Los Angeles",
					"resolutions": {
						"resolutionsPerAuthority": [
							{
								"authority": "amzn1.er-authority.echo-sdk.amzn1.ask.skill.51eb4a26-1810-4c08-a350-4fb1aec7bb80.AMAZON.US_CITY",
								"status": {
									"code": "ER_SUCCESS_MATCH"
								},
								"values": [
									{
										"value": {
											"name": "Los Angeles",
											"id": "d0aa2dffa0da83f1f34681308d04db5d"
										}
									}
								]
							}
						]
					},
					"confirmationStatus": "NONE",
					"source": "USER"
				},
				"fromcity": {
					"name": "fromcity",
					"value": "San Diego",
					"resolutions": {
						"resolutionsPerAuthority": [
							{
								"authority": "amzn1.er-authority.echo-sdk.amzn1.ask.skill.51eb4a26-1810-4c08-a350-4fb1aec7bb80.AMAZON.US_CITY",
								"status": {
									"code": "ER_SUCCESS_MATCH"
								},
								"values": [
									{
										"value": {
											"name": "San Diego",
											"id": "a1edff17ec0464c4c048d25d25bce75a"
										}
									}
								]
							}
						]
					},
					"confirmationStatus": "NONE",
					"source": "USER"
				}
			}
		}
	}
}

**Comment by ndg63276** [comment]
For your last comment, I suggest you switch from testing in the Alexa development console, instead test in Lambda. You can do this by:

1. In Lambda, click the down arrow where it says "Select a test event"
2. Select "Configure Test Events"
3. Choose "Create New Test Event", give it a name, and copy the JSON into the box, and click Create.
4. Finally click the Test button.

For me, the JSON in your last comment works in Lambda, but not in the Alexa development console.

For the commute, make sure you have enabled address permissions by going to the Alexa app, and:

1. go to Skills and Games from the main menu
2. click "Your Skills", then "Dev Skills", then "Google Maps"
3. Click "Settings", then "Manage Settings"
4. Enable "Device Address" and click "Save Settings"

It should then know your address, but it only works from a real Alexa device, not your phone, not from Lambda, not from Alexa dev console. Go to a real Echo, and say "Alexa, ask Google Maps how is my commute".

**Comment by sukritchakravarty** [comment]
What I am trying to do is, using your code creating a new one to find near by businesses thats why I was doing that using Skill console.

**Comment by ndg63276** [comment]
That's great and all. My skill works as it is, but only through a real Alexa device if you want to use your real address. Otherwise the permissions aren't granted.
